### PR TITLE
finished create-course

### PR DESCRIPTION
**Pull request by KemelovIsa**

### CODE REVIEW

**Review by kylychbekovi4 — APPROVED** [review]

**Review by AbdurashitovBeksultan — APPROVED** [review]

**Review by Asel-git — APPROVED** [review]

**Review by Rakatova-Nuraiym — APPROVED** [review]

**Comment by Jumanov07** [comment]
image

errors + logs!

**Comment by Jumanov07** [comment]
where adaptation and vertical scroll?

**Comment by Jumanov07** [comment]
Doesn't look like figma.

**Review by Elkhan2003 — COMMENTED** [review]
import 'react-toastify/dist/ReactToastify.css';

.then(() => {
				notifySuccess();
				setOpen(false);
				setData('');
				setText('');
				setImage('');
				setValue('');
			})
			.catch(() => {
				notifyError();
			});
			
			
			
			<Route path="/courses" element={<Courses />} />
						<Route path="/courses" element={<Cards />} />

**Pull request merged**
